<?php

namespace ApiV1Bundle\Repository;

/**
 * DatosTurnoHistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosTurnoHistoricoRepository extends \Doctrine\ORM\EntityRepository
{
}
