<?php

namespace ApiV1Bundle\Repository;

/**
 * PuntoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntoTramiteRepository extends ApiRepository
{
}
