<?php

namespace ApiV1Bundle\Repository;

/**
 * ReasignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReasignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
