<?php

namespace ApiV1Bundle\Repository;

/**
 * TurnoHistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoHistoricoRepository extends \Doctrine\ORM\EntityRepository
{
}
